---
- name: Stage Webservers 
  hosts: webservers
  become: true
  vars:
    - http_port: 80
    - max_clients: 200
  remote_user: root
  tasks:
    - name: Set new IP adress
      - ip: "{{ ip4 }}"
      - interface: enp1s0
    - name: Update DNF Package Cache
      dnf: update_cache=yes 

    - name: Install MariaDB
      dnf:
        name: mariadb-server
        state: present

    - name: Install Apache
      dnf:
        name: httpd.x86_64
        state: present

    - name: Install Apache modules
      dnf:
        name: php.x86_64
        state: present

    - name: Install Apache modules
      dnf:
        name: 
          - php-bcmath.x86_64
          - php-cli.x86_64
          - php-common.x86_64
          - php-fpm.x86_64
          - php-gd.x86_64
          - php-intl.x86_64
          - php-ldap.x86_64
          - php-mbstring.x86_64
          - php-mysqlnd.x86_64
          - php-odbc.x86_64
          - php-pear.noarch
          - php-snmp.x86_64
          - php-soap.x86_64
          - php-xml.x86_64
        state: present

